DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS engine;
DROP TABLE IF EXISTS car_contains_engine;
DROP TABLE IF EXISTS body;
DROP TABLE IF EXISTS car_has_body;
DROP TABLE IF EXISTS fuel;
DROP TABLE IF EXISTS runs_on;


